#spring:
#  application:
#    name: Api-Gateway
#  cloud:
#    gateway:
#      routes:
#        - id: Discount-Service
#          uri: lb://Discount-Service
#          predicates:
#            - Path:/coupons/**
#        - id: Main-Service
#          uri: lb://Main-Service
#          predicates:
#            - Path:/main/**
#server:
#  port: 8080
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/



server:
  port: 8080

spring:
  application:
    name: Api-Gateway
  cloud:
    gateway:
      routes:
        - id: Discount-Service
          uri: lb://Discount-Service
          predicates:
            - Path=/api/v1/coupons/**
        - id: main-service
          uri: lb://Main-Service
          predicates:
            - Path=/api/v1/main/**


#This is to configure the Eureka Client
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
#instance:
#  hostname: localhost